pretzel: 
    engine: razor

permalink: /en/blog/:category/:title/index.html
excerpt_separator: <!--more-->

title : Andrey Akinshin
author :
  name : Andrey Akinshin
  email : andrey.akinshin@gmail.com
twitter_username: andrey_akinshin