language: ruby
rvm:
- 1.9.3
branches:
  only:
  - master
script: "./build.sh"
env:
  global:
  - secure: "rCl87/FHaofh+6Il7NQbgecqMtA+1q8f1nzEJysZB6oO+nfi4yVpYqAam6w/I5ah3Gq4L1TIuTWonVbvm8LgQ9kIfMPqzJpfW9yKhHP+VZY8j6UMJHkRq1WoqBhWjOz31PRXwOeB/kbxHC529WVLGvfAAL1g4FXhEIM6XiIW5Zc="
  - POST_BUILD=true
before_script:
 - chmod +x build.sh