pretzel: 
    engine: razor

permalink: /:category1/blog/:category2/:title/index.html
paginate: 10
paginate_path: "blog/:num"
excerpt_separator: <!--more-->

title : Андрей Акиньшин
author :
  name : Andrey Akinshin
  email : andrey.akinshin@gmail.com
twitter_username: andrey_akinshin