permalink: /blog/:categories/:title 
paginate: 10
paginate_path: "blog/:num"
excerpt_separator: <!--more-->
markdown: kramdown
exclude: ["build.sh", "Gemfile"]

title : Андрей Акиньшин
author :
  name : Andrey Akinshin
  email : andrey.akinshin@gmail.com
twitter_username: andrey_akinshin

url: ""
home_path: "/"
asset_path: "/assets"

blog:
    tags:
        url: /blog/tag/
        title_prefix: "Тег: "
        layout: tag.html
    categories:
        url: /blog
        title_prefix: "Категория: "
        layout: category.html

JB :
  content_path : /blog/content
  tags_path: /blog/tag
  categories_path: /blog
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : disqus
    disqus :
      short_name : aakinshin