pretzel: 
    engine: razor

permalink: /ru/blog/:category/:title/index.html
excerpt_separator: <!--more-->

title : Андрей Акиньшин
author :
  name : Андрей Акиньшин
  email : andrey.akinshin@gmail.com
twitter_username: andrey_akinshin